# Generated by Django 3.1.2 on 2021-03-29 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=150)),
                ('metric', models.CharField(max_length=30)),
                ('order', models.CharField(choices=[('DESC', 'DESC'), ('ASC', 'ASC')], default=('DESC', 'DESC'), max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenumerationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interpolation', models.FloatField(default=0.0)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.objective')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.FloatField()),
                ('description', models.CharField(max_length=30)),
                ('consecution_percentage', models.FloatField(default=0.0)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.objective')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
