# Generated by Django 3.1.2 on 2021-03-29 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('metric', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RenumerationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Consecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.FloatField()),
                ('description', models.CharField(max_length=30)),
                ('consecution_percentage', models.FloatField()),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.objective')),
            ],
        ),
    ]
