# Generated by Django 3.1.2 on 2021-03-30 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpolationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interpolation', models.FloatField(default=0.0)),
                ('consecution_percentage', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectiveGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=30)),
                ('consecution_percentage', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='renumerationresult',
            name='objective',
        ),
        migrations.AlterField(
            model_name='objective',
            name='order',
            field=models.CharField(choices=[('Descendente', 'DESC'), ('Ascendente', 'ASC')], default=('Descendente', 'DESC'), max_length=20),
        ),
        migrations.DeleteModel(
            name='Consecution',
        ),
        migrations.DeleteModel(
            name='RenumerationResult',
        ),
        migrations.AddField(
            model_name='objectivegoal',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.objective'),
        ),
        migrations.AddField(
            model_name='interpolationresult',
            name='objective',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.objective'),
        ),
    ]
