# Generated by Django 3.1.2 on 2021-03-30 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210330_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='order',
        ),
    ]
